---
title: "Olfaction First Pass"
output: html_notebook
---
# Initializations
```{r, deps}
library(scales) # for oob=squish trick (see: https://github.com/tidyverse/ggplot2/issues/866)
library(viridis) # pretty scales!
library(MASS)
library(stringr)
library(magrittr)
library(modelr)
library(tidyverse)


theme_pub <- function(base_size = 13, base_family = "") {
  require(grid)
  # based on https://github.com/noamross/noamtools/blob/master/R/theme_nr.R
  # start with theme_bw and modify from there!
  theme_bw(base_size = base_size, base_family = base_family) +# %+replace%
    theme(
      # grid lines
      panel.grid.major.x = element_line(colour="#ECECEC", size=0.5, linetype=1),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_line(colour="#ECECEC", size=0.5, linetype=1),
      panel.background   = element_blank(),

      # axis options
      axis.ticks.y   = element_blank(),
      axis.title.x   = element_text(size=rel(2.25), vjust=0.25),
      axis.title.y   = element_text(size=rel(2.25), vjust=0.35),
      axis.text      = element_text(color="black", size=rel(1.5)),

      # legend options
      legend.title    = element_blank(),
      legend.key      = element_rect(fill="white"),
      legend.key.size = unit(1, "cm"),
      legend.text     = element_text(size=rel(2)),

      # facet options
      strip.text = element_text(size=rel(2)),

      # title options
      plot.title = element_text(size=rel(3), vjust=0.25, hjust=0.5)
      )
  }

# set the theme and brewer color
theme_set(theme_pub())
```

## Load Everything
```{r, loading}
# only for local development
setwd('~/Dropbox/UCLA/Kosuri/olfaction/analysis/')
counts.per.idx <- read_delim('output/idx-bcs-counts.txt', delim = ' ',
                             col_names = c('Index', 'Barcode', 'Count'))
or.key <- read_delim('barcode-or.txt', delim = ' ')
idx.key <- inner_join(
  read_delim('index-key.txt', delim = ' '),
  read_delim('output/idx-counts.txt', delim = ' ', col_names = c('Index', 'Reads')),
  by = 'Index'
)

or.counts <- counts.per.idx %>%
    inner_join(or.key, by = 'Barcode') %>%
    inner_join(idx.key, by = 'Index')
```

# Basic Info
## Correlations
```{r, corrs}
or.counts %>% 
  mutate(
    Norm = Count / Reads,  
    Repeat = if_else(Repeat == 1, 'One', 'Two')
  ) %>% 
  select(OR, Drug, Conc, Repeat, Norm) %>% 
  spread(Repeat, Norm) %>%
  filter(!is.na(Two)) %T>% 
  {
    group_by(., Drug, Conc) %>%
      summarise(Cor = cor(One, Two, use = 'complete')) %>%
      print
  } %>%
  ggplot(aes(x=One, y=Two)) + 
  geom_point() + 
  facet_wrap(Drug ~ Conc) +
  geom_abline(color='red')
```
## Rough HeatMap
```{r, per-or}
# take median expression level for each variant across conditions
per.or <- counts.per.idx %>%
  inner_join(or.key, by = 'Barcode') %>%
  inner_join(idx.key, by = 'Index') %>%
  group_by(OR, Drug, Conc) %>%
  summarise(Norm = mean(Count / Reads)) %>%
  ungroup()
```

Here we will plot the normallized read counts of the negative data vs the drug condition. We expect that highly activated ORs will spike relative to the negative.

```{r, drug-lm}
per.or %>%
  filter(Drug == 'Negative') %>%
  select(OR, Zero = Norm) %>%
  inner_join(per.or, by = 'OR') %>%
  ggplot(aes(x=Zero, y=Norm, color=Conc)) +
  geom_point() +
  geom_abline(color = 'red') + 
  geom_smooth(se=F, method = 'lm', linetype = 'dashed') +
  geom_smooth(se=F, method = 'rlm') +
  facet_wrap(~ Drug)
```

We see that the robust regression (solid line) provides a more accurate fit than the standard LM.

```{r, lm_heatmap}
per.or %>%
  filter(Drug == 'Negative') %>%
  select(OR, Zero = Norm) %>%
  inner_join(per.or, by = 'OR') %>%
  group_by(Drug, Conc) %>%
  nest() %>%
  filter(Drug != 'Negative') %>%
  mutate(LM = map(data, ~ rlm(Norm ~ Zero, data = .x, maxit = 40)),
         Preds = map2(data, LM, add_predictions)) %>%
  unnest(Preds) %>%
  mutate(LM_Norm = (Norm - pred) / pred) %>%
  ggplot(aes(x = OR, y = interaction(Conc, Drug), fill = LM_Norm)) +
  geom_raster() +
  scale_fill_distiller(direction = 1) +
  theme(axis.text.x = element_text(angle = 315, hjust = 0.1, vjust = 0.9))
```


```{r, heatmap}
per.or %>% 
  filter(Drug == 'Negative') %>% 
  select(OR, Zero = Norm) %>% 
  right_join(per.or, by = 'OR') %>% 
  mutate(Fold = log2(Norm / Zero)) %>% 
  filter(Drug != 'Negative', OR != '181_1') %>% # dead OR
  ggplot(aes(x = OR, y = interaction(Conc, Drug), fill=Fold)) + 
  geom_raster() + 
  #scale_fill_viridis() +
  scale_fill_distiller(palette = "RdBu", limits = c(0,2), direction = 1, oob=squish) + 
  #scale_fill_distiller(palette = "RdBu", direction = 1) +
  theme(axis.text.x = element_text(angle = 315, hjust = 0.1, vjust = 0.9)) +
  labs(y = 'Treatment')
```
